### ISSUE TITLE
TS2339 [ERROR]: Property 'methodId' does not exist on type 'never'

### ISSUE THREAD

**Issue by quaos** [lenkan/deno-amqp#27]
After upgraded Deno to v1.13.2, my repository that uses this library fails to run with these error messages:

```
TS2339 [ERROR]: Property 'methodId' does not exist on type 'never'.
            "Unknown method " + method!.methodId + " for class 'confirm'",
                                        ~~~~~~~~
    at https://deno.land/x/amqp@v0.16.0/src/amqp_codec.ts:2570:41

TS2339 [ERROR]: Property 'classId' does not exist on type 'never'.
      throw new Error("Unknown class " + method!.classId);
                                                 ~~~~~~~
    at https://deno.land/x/amqp@v0.16.0/src/amqp_codec.ts:2577:50

# similar errors in various positions ...
```
[tsconfig.json.zip](https://github.com/lenkan/deno-amqp/files/7096172/tsconfig.json.zip)

I've attached tsconfig.json used in my project.

Please help check this issue. Thanks!

**Comment by lenkan** [comment]
Thanks for reporting. This is resolved in #28, I will publish a new version soon.
